ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "heroMediaMode" TEXT NOT NULL DEFAULT 'image';
ALTER TABLE "MediaAsset" ADD COLUMN IF NOT EXISTS "kind" TEXT NOT NULL DEFAULT 'image';
ALTER TABLE "MediaAsset" ADD COLUMN IF NOT EXISTS "posterSource" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "displayDate" DATE;
